### ISSUE TITLE
前端知识点整理

### ISSUE THREAD

**Issue by xianggemingnan** [xianggemingnan/blog#1]
#  前端入门指南
###  1.1 HTML基础
**必须掌握的一些名称**
*  HTML 页面骨架
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Document</title>
        <meta name="keywords"content=""/>
        <meta name="description"content=""/>
        <meta name="viewport"content="width=device-width"/>
        <link rel="stylesheet"href="CSS 路径"/>
        <link rel="shortcut icon"href="网页图标.ico"/>
    </head>
    <body>
    </body>
</html>
```

* HTML 文档

HTML 文档 = 网页
`<html> `与 `</html>` 之间的文本描述网页
`<body> `与 `</body>` 之间的文本是可见的页面内容
`<h1>` 与 `</h1>`  之间的文本被显示为标题
`<p>` 与 `</p>` 之间的文本被显示为段落

* HTML 元素

定义：HTML 元素指的是从开始标签（start tag）到结束标签（end tag）的所有代码。

```html
<p>element</p>
```

* HTML标签，开始标签，结束标签

```html
<html>
    <p></p>
</html>
```

* HTML 属性，属性值

HTML 标签可以拥有属性
属性总是以名称/值对的形式出现，比如：`name="value"`
属性总是在 HTML 元素的开始标签中规定
使用小写属性
始终为属性值加引号
```html
<a href="http://www.w3school.com.cn">This is a link</a>
```
* HTML 常见属性（'id','class','style''title''）

|属性|值|描述|
|---|---|---|
|class|classname|规定元素的类名|
|id|id|规定元素的唯一 id|
|style|style——definition|规定元素的行内样式（inline style）|
|title|text|规定元素的额外信息（可在工具提示中显示）|

```html
<div title="GitHub" class="shortcut"></div>
<div id="part1"></div>
<h1 style="color:blue; text-align:center">This is a header</h1>
```
* HTML 标签嵌套
```html
<html>
    <body>
        <p></p>
    </body>
</html>
```

* HTML 块级元素，行内元素
    1. 块级元素
    一般用来搭建网站架构、布局、承载内容……它包括以下这些标签：
    常用的有：　div、p、ul、ol、li、dl、dt、dd、fieldset、form、h1~h6、hr、table
    另外还有：address、isindex、menu、noframes、noscript、pre、blockquote、center、dir、
    2. 行内元素
    一般用在网站内容之中的某些细节或部位，用以“强调、区分样式、上标、下标、锚点”等等，下面这些标签都属于内嵌元素：
    常用的有：　span、a、b、strong、i、em、label、textarea、small、img、input（img和input,这里放在内嵌元素里了）
    另外还有：abbr、acronym、bdo、big、br、cite、code、dfn、font、kbd、q、s、samp、select、strike、sub、sup、tt、u、var
```html
<div>
    <div>
        <span></span>
    </div>
</div>
```

**必须掌握的一些标签**
* HTML 文本标题，段落
    请确保将 HTML heading 标签只用于标题。不要仅仅是为了产生粗体或大号的文本而使用标题。搜索引擎使用标题为您的网页的结构和      内容编制索引。因为用户可以通过标题来快速浏览您的网页，所以用标题来呈现文档结构是很重要的。应该将 h1 用作主标题（最重要       的），其后是 h2（次重要的），再其次是 h3，以此类推。
```html
<h1>标题</h1>
<p>段落</p>
```
* HTML 文本链接

```html
<a href="url">Link text</a>
```
* HTML 文本格式化（粗体，斜体，删除字，span）
<span> 标签被用来组合文档中的行内元素。
提示：请使用 <span> 来组合行内元素，以便通过样式来格式化它们。
注释：span 没有固定的格式表现。当对它应用样式时，它才会产生视觉上的变化。
```html
<b>粗体</b>
<i>斜体</i>
<del>删除字</del>
<p>
    <span>
        some text.
    </span>
    some other text.
</p>
```
* HTML 图片
```html
<img src="url" />
<img src="boat.gif" alt="Big Boat">
```
alt 属性用来为图像定义一串预备的可替换的文本。替换文本属性的值是用户定义的。

* HTML 注释
    在开始标签中有一个惊叹号，但是结束标签中没有。
    浏览器不会显示注释，但是能够帮助记录您的 HTML 文档。
    您可以利用注释在 HTML 中放置通知和提醒信息
    注释对于 HTML 纠错也大有帮助，因为您可以一次注释一行 HTML 代码，以搜索错误
```html
<!-- 在此处写注释 -->
<!--[if IE 8]>
    .... some HTML here ....
<![endif]-->
```
* HTML 有序/无序列表和嵌套列表

```html
<ol>
    <li>Coffee</li>
    <li>Milk</li>
</ol>

<ul>
    <li>Coffee</li>
    <li>Milk</li>
</ul>

<ul>
    <li>咖啡</li>
    <li>茶
        <ul>
        <li>红茶</li>
        <li>绿茶
            <ul>
            <li>中国茶</li>
            <li>非洲茶</li>
            </ul>
        </li>
        </ul>
    </li>
    <li>牛奶</li>
</ul>
```
* HTML 其他标签（折行符，水平线）
```html
<br/>
<hr/>
```

**必须掌了解**
* HTML 内联框架

```html
<iframe src="demo_iframe.htm" 
width="200" height="200" 
frameborder="0"></iframe>

<iframe src="demo_iframe.htm" name="iframe_a"></iframe>
<p><a href="http://www.w3school.com.cn" target="iframe_a">W3School.com.cn</a></p>
```
* HTML 脚本（属性）
    <script> 标签用于定义客户端脚本，比如 JavaScript。
    script 元素既可包含脚本语句，也可通过 src 属性指向外部脚本文件。
    必需的 type 属性规定脚本的 MIME 类型。
    JavaScript 最常用于图片操作、表单验证以及内容动态更新。
```html
<script type="text/javascript">
document.write("Hello World!")
</script>

<script type="text/javascript">
document.write("Hello World!")
</script>
<noscript>Your browser does not support JavaScript!</noscript>
```
* HTML 头部（title，meta，link，base，script，style）

|标签|描述|
|---|---|
|head|定义关于文档的信息|
|title|定义文档标题|
|base|定义页面上所有链接的默认地址或默认目标|
|link|定义文档与外部资源之间的关系|
|meta|定义关于 HTML 文档的元数据|
|script|定义客户端脚本|
|style|定义文档的样式信息|
```html
<head>
    <meta charset="utf-8"/>
    
    <title>Document</title>
    
    <meta name="keywords"content=""/>
    <meta name="description"content=""/>
    <meta name="viewport"content="width = device-width"/>
    
    <link rel="stylesheet"href="CSS 路径"/>
    <link rel="shortcut icon"href="网页图标.ico"/>
    
    <base href="http://www.w3school.com.cn/i/" />
    <base target="_blank" />
   
   <script type="text/javascript">
    document.write("Hello World!")
    </script>
   
   <style type="text/css">
    h1 {color:red}
    p {color:blue}
    </style>
</head>
```
* HTML 字符实体（&lt；/&gt；/&nbsp； ...）

|显示结果|描述|实体名称|实体编号|
|---|---|---|---|
| |空格| `&nbsp;`|`&#160;`|
|`<`|小于|`&lt;`|`&#60;`|
|`>`|大于|`&gt;`||
|`©`|版权|`&copy;`|`&#169;`|
|`®`|注册商标|`&reg;`|`&#174;`|
```html
<p> &nbsp;  &#160;
       &lt;      &#60;
       &gt;     &#62;
       &copy;  &#169;
       &reg;    &#174;
</p>
```

**先了解**
* HTML 布局
    div , CSS , HTML5 , 表格 
```html
<div id="header">
<h1>City Gallery</h1>
</div>

<footer>
Copyright W3School.com.cn
</footer>

<table class="lamp">
<tr>
  <th>
    <img src="./images/lamp.jpg" alt="Note" style="height : 32px ; width : 32px">
  </th>
  <td>
    The table element was not designed to be a layout tool.
  </td>
</tr>
</table>
```
```CSS
#nav {
    line-height:30px;
    background-color:#eeeeee;
    height:300px;
    width:100px;
    float:left;
    padding:5px; 
```
* HTML 响应式设计

###  1.2 HTML表格
**必须掌握**
* HTML 表格标签结构
```html
<table border="1">
    <tr>
        <td>row 1, cell 1</td>
        <td>row 1, cell 2</td>
    </tr>
    <tr>
        <td>row 2, cell 1</td>
        <td>row 2, cell 2</td>
    </tr>
</table>
```
* 绘制简单表格
```html
<table border="1">
    <tr>
      <td>100</td>
      <td>200</td>
      <td>300</td>
    </tr>
    <tr>
      <td>400</td>
      <td>500</td>
      <td>600</td>
    </tr>
</table>
```
* 设置表格属性（边框，表头）
如果不定义边框属性，表格将不显示边框。有时这很有用，但是大多数时候，我们希望显示边框。
表格的表头使用 <th> 标签进行定义。
```html
<table border="1">
<th>Heading</th>
<th>Another Heading</th>
```

* 设置跨行跨列单元格
```html
<th colspan="2">一行两列单元格</th>
<th rowspan="2">两行一列单元格</th>
```

* 设置单元格间隔，边距，背景颜色
```html
<table border="1" 
cellspacing="10">
<table border="1" 
cellpadding="10">

<table border="1" 
bgcolor="red">
<table border="1" 
background="/i/eg_bg_07.gif">

<td bgcolor="red">First</td>
<td background="/i/eg_bg_07.gif">
```

### 1.3 HTML表单
**必须掌握**
* 表单结构
```html
<form>
 .
form elements
 .
</form>
```

* input 元素输入类型，输入属性
`<input type="text">` 定义用于文本输入的单行输入字段
`<input type="radio"> `定义单选按钮。
`<input type="submit">` 定义用于向表单处理程序（`form-handler`）提交表单的按钮。
`action` 属性定义在提交表单时执行的动作。

`method` 属性规定在提交表单时所用的 HTTP 方法（GET 或 POST）

当您使用 GET 时，表单数据在页面地址栏中是可见的
注释：GET 最适合少量数据的提交。浏览器会设定容量限制。
您能够使用 GET（默认方法）：
如果表单提交是被动的（比如搜索引擎查询），并且没有敏感信息。
当您使用 GET 时，表单数据在页面地址栏中是可见的：

您应该使用 POST：
如果表单正在更新数据，或者包含敏感信息（例如密码）。
POST 的安全性更加，因为在页面地址栏中被提交的数据是不可见的。
```html
 First name:<br>
<input type="text" name="firstname">
<input type="radio" name="sex" value="male" checked>Male
<input type="submit" value="Submit">
<form action="action_page.php">
<form action="action_page.php" method="GET/POST">
```
<fieldset> 元素组合表单中的相关数据
<legend> 元素为 <fieldset> 元素定义标题。
```html
<fieldset>
<legend>Personal information:</legend>
```
**HTML Form 属性**
```html
<form action="action_page.php" method="GET" target="_blank" accept-charset="UTF-8"
ectype="application/x-www-form-urlencoded" autocomplete="off" novalidate>
.
form elements
 .
</form> 
```
* textarea 元素 - 多行文本输入
```html
<textarea name="message" rows="10" cols="30">
The cat was playing in the garden.
</textarea>
```

* select 元素 - 下拉列表
```HTML
<select name="cars">
<option value="volvo">Volvo</option>
<option value="saab">Saab</option>
<option value="fiat">Fiat</option>
<option value="audi">Audi</option>
</select>
```

* button 元素 - 点击按钮
```html
<button type="button" onclick="alert('Hello World!')">Click Me!</button>
```
* 表单元素的属性

* 提交表单
```html
<input type="text" name="firstname" value="Mickey">
```
###  1.4 HTML其他知识
* 文件路径（相对路径，绝对路径）
```html
<img src="/images/picture.jpg" alt="flower">
<img src="images/picture.jpg" alt="flower">
<img src="../images/picture.jpg" alt="flower">
<img src="https://www.w3school.com.cn/images/picture.jpg" alt="flower">
```

* CSS 和 JS 脚本文件引入
```html
<script type="text/javascript">
document.write("Hello World!")
</script>
<script type="text/javascript">
document.write("Hello World!")
</script>
<noscript>Your browser does not support JavaScript!</noscript>
```
* URL 格式
scheme://host.domain:port/path/filename
scheme - 定义因特网服务的类型。最常见的类型是 http
host - 定义域主机（http 的默认主机是 www）
domain - 定义因特网域名，比如 w3school.com.cn
:port - 定义主机上的端口号（http 的默认端口号是 80）
path - 定义服务器上的路径（如果省略，则文档必须位于网站的根目录中）。
filename - 定义文档/资源的名称
### 2.1 CSS介绍
* CSS 概念
Cascading Style Sheets
层叠 样式 表

* CSS 如何试用（常见四种方式）
浏览器缺省设置
外部样式表
内部样式表（位于 <head> 标签内部）
内联样式（在 HTML 元素内部）

* CSS 语法和注意点
CSS 规则由两个主要的部分构成：选择器，以及一条或多条声明。![577862b77a60b60f783a3e544a96b242.gif](en-resource://database/496:1)

### 2.2 CSS基础
* CSS 基础选择器（派生，id，类，属性选择器）
```css
li strong {
    font-style: italic;
    font-weight: normal;
  }
  
#red {
    color:red;
    }


.center {
    text-align: center
    }

[title]
    {
    color:red;
}
```

* CSS 相关样式（文本颜色，字号，对齐方式...）

|属性|描述|
|---|---|
|color|设置文本颜色|
|direction|设置文本方向|
|line-height|设置行高|
|letter-spacing|设置字符间距|
|text-align|对齐元素中的文本|
|text-decoration|向文本添加修饰|
|text-indent|缩进元素中文本的首行
|text-transform|控制元素中的字母|
|white-space|设置元素中空白的处理方式|
|word-spacing|设置字间距|

* CSS 列表，表格，轮廓样式

|属性|描述|
|---|---|
|list-style|简写属性。用于把所有用于列表的属性设置于一个声明中|
|list-style-image|将图像设置为列表项标志|
|list-style-position|设置列表中列表项标志的位置|
|list-style-type|设置列表项标志的类型|

|属性|描述|
|---|---|
|border-collapse|设置是否把表格边框合并为单一的边框|
|border-spacing|设置分隔单元格边框的距离|
|caption-死的|设置表格标题的位置|
|empty-cells|设置是否显示表格中的空单元格|
|table-layout|设置显示单元、行、列的算法|

|属性|描述|
|---|---|
|outline|在一个声明中设置所有的轮廓属性|
|outline-color|设置轮廓的颜色|
|outline-style|设置轮廓的样式|
|outline-width|设置轮廓的宽度|

* CSS 框模型（概念，内边距，外边距，外边距合并）
![c90305a4d3ccc63f2f3dec7db4d7cdfd.gif](en-resource://database/498:1)
元素框的最内部分是实际的内容，直接包围内容的是内边距。内边距呈现了元素的背景。内边距的边缘是边框。边框以外是外边距，外边距默认是透明的，因此不会遮挡其后的任何元素。提示：背景应用于由内容和内边距、边框组成的区域。

CSS padding 属性定义元素的内边距。padding 属性接受长度值或百分比值，但不允许使用负值。
```css
h1 {padding: 10px 0.25em 2ex 20%;}
```
设置外边距的最简单的方法就是使用 margin 属性。
```css
h1 {margin : 10px 0px 15px 5px;}
```
外边距合并指的是，当两个垂直外边距相遇时，它们将形成一个外边距。合并后的外边距的高度等于两个发生合并的外边距的高度中的较大者。
* CSS 定位（绝对定位，相对定位，浮动）
```css
h2.pos_abs {
    position:absolute;
    left:100px;
    top:150px
}

h2.pos_left {
    position:relative;
    left:-20px
}

img
  {
  float:right;
  }
  
img
  {
  float:left;
  clear:both;
  }
```
### 2.3 CSS选择器
* CSS 选择器分组
```css
body, h2, p, table, th, td, pre, strong, em {
    color:gray;
    }
```
* CSS 其他选择器（后代，子元素，相邻兄弟选择器）
1. 如果您希望只对 h1 元素中的 em 元素应用样式
2. 如果您不希望选择任意的后代元素，而是希望缩小范围，只选择某个元素的子元素，请使用子元素选择器
3. 如果需要选择紧接在另一个元素后的元素，而且二者有相同的父元素，可以使用相邻兄弟选择器
```css
h1 em {color:red;}
h1 > strong {color:red;}
h1 + p {margin-top:50px;}
```
* CSS 伪类/伪元素
CSS 伪类用于向某些选择器添加特殊的效果
CSS 伪元素用于向某些选择器设置特殊效果
```css
selector : pseudo-class {property: value}
selector.class : pseudo-class {property: value}

selector:pseudo-element {property:value;}
selector.class:pseudo-element {property:value;}
```
### 2.5 CSS高级
* CSS 对齐（多种方式，水平对齐，垂直对齐）

块元素指的是占据全部可用宽度的元素，并且在其前后都会换行。
使用 margin 属性来水平对齐
使用 position 属性进行左和右对齐
使用 float 属性来进行左和右对齐
```css
.center
    {
    margin-left:auto;
    margin-right:auto;
    width:70%;
    background-color:#b0e0e6;
}

.right
    {
    position:absolute;
    right:0px;
    width:300px;
    background-color:#b0e0e6;
}

.right
    {
    float:right;
    width:300px;
    background-color:#b0e0e6;
}
```
* CSS 尺寸（宽度，高度）

|属性|描述|
|---|---|
|height|设置元素的高度|
|width|设置元素的宽度|
|line-height|设置行高|
|max-height|设置元素的最大高度|
|max-width|设置元素的最大宽度|
|min-height|设置元素的最小高度|
|min-width|设置元素的最小宽度|

* CSS 导航栏（水平，垂直）
导航栏 = 链接列表
```html
<ul>
    <li><a href="default.asp">Home</a></li>
    <li><a href="news.asp">News</a></li>
    <li><a href="contact.asp">Contact</a></li>
    <li><a href="about.asp">About</a></li>
</ul>
```
```css
ul {
    list-style-type:none;
    margin:0;
    padding:0;
}

li {
    display:inline;
}
a {
    display:block;
    width:60px;
}
```

* CSS 图片透明
定义透明效果的 CSS3 属性是 opacity。
```css
img
    {
    opacity:0.4;
    filter:alpha(opacity=40); /* 针对 IE8 以及更早的版本 */
}
img:hover
    {
    opacity:1.0;
    filter:alpha(opacity=100); /* 针对 IE8 以及更早的版本 */
}
```

* CSS 分类（6种情况）

|属性|描述|
|---|---|
|clear|设置一个元素的侧面是否允许其他的浮动元素|
|cursor|规定当指向某元素之上时显示的指针类型|
|display|设置是否及如何显示元素|
|float|定义元素在哪个方向浮动|
|position|把元素放置到一个静态的、相对的、绝对的或固定的位置中|
|visibility|设置元素是否可见或不可见|

##  三、高级页面结构层 HTML5
* HTML5 介绍（概念，新特性）
1. HTML5 是下一代的 HTML。
HTML5 将成为 HTML、XHTML 以及 HTML DOM 的新标准。HTML 的上一个版本诞生于 1999 年。自从那以后，Web 世界已经经历了巨变。HTML5 仍处于完善之中。然而，大部分现代浏览器已经具备了某些 HTML5 支持。
2. 新特性
用于绘画的 canvas 元素
用于媒介回放的 video 和 audio 元素
对本地离线存储的更好的支持
新的特殊内容元素，比如 article、footer、header、nav、section
新的表单控件，比如 calendar、date、time、email、url、search
* HTML5 多媒体（视频，音频）

controls 属性供添加播放、暂停和音量控件。包含宽度和高度属性也是不错的主意。<video> 与 </video> 之间插入的内容是供不支持 video 元素的浏览器显示的
```html
<video width="320" height="240" controls="controls">
  <source src="movie.ogg" type="video/ogg">
  <source src="movie.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>

<audio controls="controls">
  <source src="song.ogg" type="audio/ogg">
  <source src="song.mp3" type="audio/mpeg">
Your browser does not support the audio tag.
</audio>
```
* HTML5 画图（Canvas，SVG）
Canvas 与 SVG 的比较
下表列出了 canvas 与 SVG 之间的一些不同之处。
**Canvas**
依赖分辨率
不支持事件处理器
弱的文本渲染能力
能够以 .png 或 .jpg 格式保存结果图像
最适合图像密集型的游戏，其中的许多对象会被频繁重绘
**SVG**
不依赖分辨率
支持事件处理器最适合带有大型渲染区域的应用程序（比如谷歌地图）
复杂度高会减慢渲染速度（任何过度使用 DOM 的应用都不快）
不适合游戏应用

* HTML5 新表单（输入类型，元素，属性）

##  四、高级页面化妆师 CSS3
* CSS3 介绍（主要模块）
选择器
框模型
背景和边框
文本效果
2D/3D 转换
动画
多列布局
用户界面

* CSS3 边框框（新属性，兼容问题）
border-radius
box-shadow
border-image
```css
div {
border-radius:25px;
box-shadow: 10px 10px 5px #888888;
border-image:url(border.png) 30 30 round;
}
```
* CSS3 背景（新属性，兼容问题）
background-size属性规定背景图片的尺寸。
background-origin属性规定背景图片的定位区域。
```css
body { 
    background-size:40% 100%;
    background-size:63px 100px;
    background-image:url(bg_flower.gif),url(bg_flower_2.gif);
}
```
* CSS3 文本效果（新属性，兼容问题）
text-shadow
word-wrap
```css
h1 {
    text-shadow: 5px 5px 5px #FF0000;
}
p {word-wrap:break-word;}
```
* CSS3 转换（2D转换，3D转换）
1. 2D转换
`translate()`
rotate()
scale()
skew()
matrix()
```css
div {
transform: rotate(30deg);
transform: translate(50px,100px);
transform: scale(2,4);
transform: skew(30deg,20deg);
transform:matrix(0.866,0.5,-0.5,0.866,0,0);
}
```
2. 3D转换
rotateX()
rotateY()
```css
div {
    transform: rotateX(120deg);
    transform: rotateY(130deg);
}
```
* CSS3 过度

|属性|描述|
|---|---|
|transition|简写属性，用于在一个属性中设置四个过度属性|
|transition-property|规定应用过度的 CSS 属性的名称|
|transition-duration|定义过度效果花费的时间。默认0|
|transition-timing-function|规定过度效果的时间曲线。默认`ease`|
|transition-delay|规定过度效果何时开始。默认0|
```css
div {
    transition-property: width;
    transition-duration: 1s;
    transition-timing-function: linear;
    transition-delay: 2s;
}
```
* CSS3 动画
```css
div {
    animation-name: myfirst;
    animation-duration: 5s;
    animation-timing-function: linear;
    animation-delay: 2s;
    animation-iteration-count: infinite;
    animation-direction: alternate;
    animation-play-state: running;
}
```

* CSS3 字体
在新的 @font-face 规则中，您必须首先定义字体的名称（比如 myFirstFont），然后指向该字体文件。
```html
<style> 
@font-face
{
font-family: myFirstFont;
src: url('Sansation_Light.ttf'),
     url('Sansation_Light.eot'); /* IE9+ */
}

div
{
font-family:myFirstFont;
}
</style>
```

* CSS3 单位（尺寸单位试用场景）
resize 属性规定是否可由用户调整元素尺寸。
```css
div
{
resize:both;
overflow:auto;
}
```
###  5.1 JavaScript 介绍
* JS 概念
JavaScript 是属于 HTML 和 Web 的编程语言。

* JS 如何使用（常见4种方式）
1. head
2. body
3. 外部脚本myScript.js
4. 外部引用
```js
<script src="myScript.js"></script>
<script src="https://www.w3school.com.cn/js/myScript1.js"></script>
```
* JS 注意点
